import blockContent from './blockContent'
import category from './category'
import products from './products'
import author from './author'
import empresa from './empresa'
import social from './social'
import inicio from './inicio'
import blog from './blog'
import contact from './contact'
import aviso from './aviso'
import post from './post'
import postCategory from './post-category'
import experiencia from './experiencia'
import ubicacion from './ubicacion'
import resorts from './resorts'
import socios from './socios'
import gracias from './gracias'

export const schemaTypes = [inicio, blog, contact, aviso, products, author, category, blockContent, social, empresa, post, postCategory, experiencia, ubicacion, resorts, socios, gracias]
